export const LIVE_HEARTBEAT_INTERVAL_MS = 30_000;
export const LIVE_HEARTBEAT_TIMEOUT_MS = 10_000;
export const DISCONNECT_GRACE_MS = 45_000;
export const DISCONNECT_CLEANUP_CRON_PATTERN = "*/5 * * * * *";
export const SERVER_RESTART_RECONNECT_AFTER_MS = 1_000;
export const SERVER_RESTART_CLOSE_CODE = 1012;
